"""
Constants used across the SwimAnalyzer AI application.
"""
from typing import Tuple

# UI Settings
APP_TITLE = "SwimAnalyzer AI"
APP_VERSION = "0.1.0-alpha"

# Drawing Colors (BGR format for OpenCV)
COLOR_RED: Tuple[int, int, int] = (0, 0, 255)
COLOR_GREEN: Tuple[int, int, int] = (0, 255, 0)
COLOR_BLUE: Tuple[int, int, int] = (255, 0, 0)
COLOR_YELLOW: Tuple[int, int, int] = (0, 255, 255)
COLOR_WHITE: Tuple[int, int, int] = (255, 255, 255)

# Drawing Thicknesses
THICKNESS_LANDMARK = 2
THICKNESS_CONNECTION = 2

# Video Processing
DEFAULT_FPS = 30.0

# Scoring Thresholds
MAX_SCORE = 100.0
DEFAULT_PENALTY_SCORE = 50.0

# Biomechanics Optimal Ranges
PULL_ELBOW_MIN_ANGLE = 90.0
PULL_ELBOW_MAX_ANGLE = 120.0

RECOVERY_SHOULDER_MIN_ANGLE = 140.0
RECOVERY_SHOULDER_MAX_ANGLE = 180.0

KNEE_BEND_MIN_ANGLE = 130.0
KNEE_BEND_MAX_ANGLE = 175.0

SYMMETRY_SCORE_PENALTY_THRESHOLD = 80.0

# Feedback Thresholds
SCORE_THRESHOLD_EXCELLENT = 90.0
SCORE_THRESHOLD_GOOD = 75.0
SCORE_THRESHOLD_FAIR = 60.0

# Reliability Thresholds
RELIABILITY_MIN_ACCEPTABLE_SCORE = 50.0
INVALID_FRAMES_RATIO_THRESHOLD = 0.25
RELIABILITY_DROP_PENALTY = 0.8
RELIABILITY_POOR_VQA_CAP = 66.0
PHASE_CONFIDENCE_WARNING_THRESHOLD = 0.50
SCORE_CAP_LOW_CONFIDENCE = 75.0
MIN_STROKE_CYCLES = 2
MIN_RELIABILITY_FOR_RECOMMENDATIONS = 40.0
MIN_CONFIDENCE_FOR_POSE = 50.0
FRAME_COVERAGE_WEIGHT = 0.7
PHASE_CONFIDENCE_WEIGHT = 0.3

CONFIDENCE_HIGH_THRESHOLD = 80.0
CONFIDENCE_MEDIUM_THRESHOLD = 50.0
RELIABILITY_HIGH_THRESHOLD = 70.0
RELIABILITY_MEDIUM_THRESHOLD = 40.0
