"""
Generates the comprehensive machine-readable biomechanics metric baseline JSON.
Step 64 - Biomechanics Metric Audit.
"""
import json
from pathlib import Path

def create_baseline():
    baseline = {
        "schema_version": "1.0.0",
        "step": "STEP_64_BIOMECHANICS_METRIC_AUDIT",
        "pose_backend": "MediaPipe_Tasks_API_Only",
        "total_metrics_audited": 41,
        "classification_summary": {
            "VALID": 11,
            "VALID_WITH_LIMITATIONS": 27,
            "NEEDS_VALIDATION": 2,
            "INCORRECT": 0,
            "UNVERIFIED": 1
        },
        "metrics": [
            {
                "name": "left_elbow",
                "category": "joint_angles",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "calculate_all_angles / _calculate_joint_angles",
                "formula": "interior_angle(L_SHOULDER[11], L_ELBOW[13], L_WRIST[15])",
                "required_landmarks": [11, 13, 15],
                "coordinate_system": "2D normalized image space [0, 1]",
                "units": "degrees",
                "temporal_assumptions": "per-frame instantaneous",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "valid pose detection with landmark visibility > 0.4",
                "confidence_handling": "flagged invalid if outside [0, 180]",
                "scientific_reference": "Maglischo (2003); Psycharakis & Sanders (2008)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Planar projection on camera sensor plane; in non-square aspect ratios (e.g. 16:9), normalized coordinates introduce minor aspect ratio scaling unless corrected by W/H."
            },
            {
                "name": "right_elbow",
                "category": "joint_angles",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "calculate_all_angles / _calculate_joint_angles",
                "formula": "interior_angle(R_SHOULDER[12], R_ELBOW[14], R_WRIST[16])",
                "required_landmarks": [12, 14, 16],
                "coordinate_system": "2D normalized image space [0, 1]",
                "units": "degrees",
                "temporal_assumptions": "per-frame instantaneous",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "valid pose detection with landmark visibility > 0.4",
                "confidence_handling": "flagged invalid if outside [0, 180]",
                "scientific_reference": "Maglischo (2003); Psycharakis & Sanders (2008)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Planar projection on camera sensor plane; sensitive to foreshortening during body roll."
            },
            {
                "name": "left_knee",
                "category": "joint_angles",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "calculate_all_angles / _calculate_joint_angles",
                "formula": "interior_angle(L_HIP[23], L_KNEE[25], L_ANKLE[27])",
                "required_landmarks": [23, 25, 27],
                "coordinate_system": "2D normalized image space [0, 1]",
                "units": "degrees",
                "temporal_assumptions": "per-frame instantaneous",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "valid pose detection with landmark visibility > 0.4",
                "confidence_handling": "flagged invalid if outside [0, 180]",
                "scientific_reference": "Maglischo (2003)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Subsurface splash/bubbles can intermittently degrade ankle landmark confidence."
            },
            {
                "name": "right_knee",
                "category": "joint_angles",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "calculate_all_angles / _calculate_joint_angles",
                "formula": "interior_angle(R_HIP[24], R_KNEE[26], R_ANKLE[28])",
                "required_landmarks": [24, 26, 28],
                "coordinate_system": "2D normalized image space [0, 1]",
                "units": "degrees",
                "temporal_assumptions": "per-frame instantaneous",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "valid pose detection with landmark visibility > 0.4",
                "confidence_handling": "flagged invalid if outside [0, 180]",
                "scientific_reference": "Maglischo (2003)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Planar projection; used for kick cycle detection and whip kick angle."
            },
            {
                "name": "left_shoulder",
                "category": "joint_angles",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "calculate_all_angles / _calculate_joint_angles",
                "formula": "interior_angle(L_HIP[23], L_SHOULDER[11], L_ELBOW[13])",
                "required_landmarks": [23, 11, 13],
                "coordinate_system": "2D normalized image space [0, 1]",
                "units": "degrees",
                "temporal_assumptions": "per-frame instantaneous",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "valid pose detection with landmark visibility > 0.4",
                "confidence_handling": "flagged invalid if outside [0, 180]",
                "scientific_reference": "Maglischo (2003)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Represents arm elevation relative to torso in 2D projection."
            },
            {
                "name": "right_shoulder",
                "category": "joint_angles",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "calculate_all_angles / _calculate_joint_angles",
                "formula": "interior_angle(R_HIP[24], R_SHOULDER[12], R_ELBOW[14])",
                "required_landmarks": [24, 12, 14],
                "coordinate_system": "2D normalized image space [0, 1]",
                "units": "degrees",
                "temporal_assumptions": "per-frame instantaneous",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "valid pose detection with landmark visibility > 0.4",
                "confidence_handling": "flagged invalid if outside [0, 180]",
                "scientific_reference": "Maglischo (2003)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Evaluated during recovery and entry phases."
            },
            {
                "name": "left_hip",
                "category": "joint_angles",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "calculate_all_angles / _calculate_joint_angles",
                "formula": "interior_angle(L_SHOULDER[11], L_HIP[23], L_KNEE[25])",
                "required_landmarks": [11, 23, 25],
                "coordinate_system": "2D normalized image space [0, 1]",
                "units": "degrees",
                "temporal_assumptions": "per-frame instantaneous",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "valid pose detection with landmark visibility > 0.4",
                "confidence_handling": "flagged invalid if outside [0, 180]",
                "scientific_reference": "Psycharakis & Sanders (2008)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Indicates trunk-to-thigh flexion / piking in water."
            },
            {
                "name": "right_hip",
                "category": "joint_angles",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "calculate_all_angles / _calculate_joint_angles",
                "formula": "interior_angle(R_SHOULDER[12], R_HIP[24], R_KNEE[26])",
                "required_landmarks": [12, 24, 26],
                "coordinate_system": "2D normalized image space [0, 1]",
                "units": "degrees",
                "temporal_assumptions": "per-frame instantaneous",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "valid pose detection with landmark visibility > 0.4",
                "confidence_handling": "flagged invalid if outside [0, 180]",
                "scientific_reference": "Psycharakis & Sanders (2008)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Indicates trunk-to-thigh flexion."
            },
            {
                "name": "body_roll",
                "category": "body_alignment",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "_estimate_body_roll",
                "formula": "abs(arctan2(R_SH.y - L_SH.y, R_SH.x - L_SH.x) * 180 / pi)",
                "required_landmarks": [11, 12],
                "coordinate_system": "2D normalized image space [0, 1]",
                "units": "degrees",
                "temporal_assumptions": "per-frame instantaneous",
                "applicable_strokes": ["Freestyle", "Backstroke"],
                "min_evidence_required": "both shoulders visible",
                "confidence_handling": "range clamped to [0, 90]",
                "scientific_reference": "Cappaert et al. (1995); Psycharakis & Sanders (2010)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Planar proxy for shoulder tilt; does not disentangle true body roll from yaw or pitch."
            },
            {
                "name": "body_roll_3d",
                "category": "spatial_3d",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "_calculate_3d_metrics",
                "formula": "torso_normal = (R_SH - L_SH) x (Mid_SH - Mid_HP); roll = arctan2(|norm_x|, |norm_y|)",
                "required_landmarks": [11, 12, 23, 24],
                "coordinate_system": "3D pose-relative (MediaPipe estimated Z)",
                "units": "degrees",
                "temporal_assumptions": "per-frame instantaneous",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "both shoulders and hips detected",
                "confidence_handling": "domain marked pose_relative_3d; clamped to [0, 90]",
                "scientific_reference": "Psycharakis & Sanders (2010); Gonjo et al. (2020)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Rigorous 3D cross-product calculation; accuracy bounded by monocular pseudo-depth estimation of Z."
            },
            {
                "name": "core_torsion_3d",
                "category": "spatial_3d",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "_calculate_3d_metrics",
                "formula": "arccos(dot(sh_vector, hp_vector) / (|sh_vector| * |hp_vector|))",
                "required_landmarks": [11, 12, 23, 24],
                "coordinate_system": "3D pose-relative",
                "units": "degrees",
                "temporal_assumptions": "per-frame instantaneous",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "both shoulders and hips detected",
                "confidence_handling": "clamped to [0, 90]",
                "scientific_reference": "Cappaert et al. (1995); Psycharakis & Sanders (2008)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Direct angular separation between shoulder transverse axis and pelvic transverse axis."
            },
            {
                "name": "hand_depth_left_3d",
                "category": "spatial_3d",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "_calculate_3d_metrics",
                "formula": "L_WRIST.z - Mid_Shoulder.z",
                "required_landmarks": [11, 12, 15],
                "coordinate_system": "3D pose-relative units",
                "units": "pose_relative_units",
                "temporal_assumptions": "per-frame instantaneous",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "left wrist and shoulders detected",
                "confidence_handling": "status marked available/unavailable",
                "scientific_reference": "UNVERIFIED",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Relative depth indicator showing whether hand is placed deeper or shallower than torso plane."
            },
            {
                "name": "hand_depth_right_3d",
                "category": "spatial_3d",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "_calculate_3d_metrics",
                "formula": "R_WRIST.z - Mid_Shoulder.z",
                "required_landmarks": [11, 12, 16],
                "coordinate_system": "3D pose-relative units",
                "units": "pose_relative_units",
                "temporal_assumptions": "per-frame instantaneous",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "right wrist and shoulders detected",
                "confidence_handling": "status marked available/unavailable",
                "scientific_reference": "UNVERIFIED",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Relative depth indicator showing whether hand is placed deeper or shallower than torso plane."
            },
            {
                "name": "stroke_phase",
                "category": "phase_detection",
                "file": "analysis/strategies/*_stroke_analyzer.py",
                "function": "analyze_frame",
                "formula": "Deterministic finite state machine with temporal hysteresis buffer (threshold = 0.1s)",
                "required_landmarks": [11, 12, 15, 16, 23, 24],
                "coordinate_system": "2D normalized coordinates + temporal velocity",
                "units": "categorical_state",
                "temporal_assumptions": "temporal buffer requires >= 2-3 consecutive frames in pending state",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "valid tracking on wrists and torso",
                "confidence_handling": "outputs phase_confidence float (0.0 - 1.0)",
                "scientific_reference": "Maglischo (2003); Chollet et al. (2000)",
                "classification": "VALID",
                "audit_notes": "Deterministic state machine prevents rapid jitter transitions between discrete phases."
            },
            {
                "name": "phase_confidence",
                "category": "phase_detection",
                "file": "analysis/strategies/*_stroke_analyzer.py",
                "function": "analyze_frame",
                "formula": "Heuristic confidence score associated with transition evidence",
                "required_landmarks": [11, 12, 15, 16],
                "coordinate_system": "scalar confidence [0.0, 1.0]",
                "units": "probability_scalar",
                "temporal_assumptions": "per-frame transition",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "active state transition",
                "confidence_handling": "used by consistency validator (Rule 1)",
                "scientific_reference": "UNVERIFIED",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Currently constant 1.0 upon valid transition, fallback 0.4 when invalid."
            },
            {
                "name": "time_in_phases",
                "category": "phase_timing",
                "file": "analysis/strategies/*_stroke_analyzer.py",
                "function": "_update_stats",
                "formula": "accumulated seconds spent in each discrete phase = dt_ms / 1000",
                "required_landmarks": [11, 12, 15, 16],
                "coordinate_system": "temporal timeline (ms)",
                "units": "seconds",
                "temporal_assumptions": "accurate video frame timestamps from TimingUtils",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "valid consecutive video frames",
                "confidence_handling": "accumulates only when current_phase is known",
                "scientific_reference": "Chollet et al. (2000) Index of Coordination",
                "classification": "VALID",
                "audit_notes": "Accurately segments stroke phases (Entry, Catch, Pull, Push, Recovery)."
            },
            {
                "name": "completed_cycles",
                "category": "phase_timing",
                "file": "analysis/strategies/*_stroke_analyzer.py",
                "function": "analyze_frame / _update_stats",
                "formula": "count of Recovery -> Entry (or Glide -> Outsweep) transitions",
                "required_landmarks": [15, 16],
                "coordinate_system": "integer count",
                "units": "cycles",
                "temporal_assumptions": "monotonic time progression",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "complete cycle loop",
                "confidence_handling": "checked by zero-fallback policy; 0 cycles = INSUFFICIENT_EVIDENCE",
                "scientific_reference": "Craig & Pendergast (1979); Maglischo (2003)",
                "classification": "VALID",
                "audit_notes": "Key gating metric for overall session score validity."
            },
            {
                "name": "average_cycle_duration_ms",
                "category": "phase_timing",
                "file": "services/analysis_service.py",
                "function": "_finalize_metrics_and_export",
                "formula": "(duration_seconds * 1000) / completed_cycles",
                "required_landmarks": [15, 16],
                "coordinate_system": "temporal duration",
                "units": "milliseconds",
                "temporal_assumptions": "completed_cycles > 0",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "at least 1 completed cycle",
                "confidence_handling": "defaults to 0.0 if completed_cycles == 0",
                "scientific_reference": "Craig & Pendergast (1979)",
                "classification": "VALID",
                "audit_notes": "Direct reciprocal of cycle stroke rate in seconds * 1000."
            },
            {
                "name": "average_phase_confidence",
                "category": "phase_timing",
                "file": "services/analysis_service.py",
                "function": "_finalize_metrics_and_export",
                "formula": "mean(phase_confidence across valid frames where phase != Unknown)",
                "required_landmarks": [15, 16],
                "coordinate_system": "scalar [0.0, 1.0]",
                "units": "ratio",
                "temporal_assumptions": "video timeline",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "valid frames with identified phase",
                "confidence_handling": "triggers Consistency Rule 1 if < 0.50",
                "scientific_reference": "UNVERIFIED",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Used as internal safety gate for scoring confidence."
            },
            {
                "name": "stroke_rate",
                "category": "global_kinematics",
                "file": "analysis/strategies/*_biomechanics_calculator.py",
                "function": "_calculate_stroke_rate",
                "formula": "cycles / duration_minutes",
                "required_landmarks": [15, 16],
                "coordinate_system": "temporal frequency",
                "units": "spm (strokes per minute / cycles per minute)",
                "temporal_assumptions": "duration > 0 and effective_fps > 0",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "at least 1 full stroke cycle detected",
                "confidence_handling": "returns value=None, status=unavailable if 0 cycles detected",
                "scientific_reference": "Craig & Pendergast (1979); Psycharakis & Sanders (2008)",
                "classification": "VALID",
                "audit_notes": "Primary swimming kinematic metric; verified against peer-reviewed population benchmarks."
            },
            {
                "name": "stroke_length",
                "category": "global_kinematics",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "_calculate_stroke_length",
                "formula": "mean(calibrate_distance(min_wrist_x, max_wrist_x)) during pull-push",
                "required_landmarks": [16, 11, 12, 27, 28],
                "coordinate_system": "relative body normalized (or physical meters if calibrated)",
                "units": "meters or body_length",
                "temporal_assumptions": "distinct pull and push phases detected",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "physical pool scale or reference body landmarks (shoulders & ankles)",
                "confidence_handling": "domain strictly gated; uncalibrated setups return body_length, never meters",
                "scientific_reference": "Craig & Pendergast (1979); Smith et al. (2002)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Measures hand reach-to-finish excursion distance per cycle; serves as relative DPS proxy."
            },
            {
                "name": "kick_frequency",
                "category": "global_kinematics",
                "file": "analysis/strategies/freestyle_biomechanics_calculator.py",
                "function": "_calculate_kick_frequency",
                "formula": "knee_flex_extension_cycles / duration_seconds",
                "required_landmarks": [24, 26, 28],
                "coordinate_system": "temporal frequency",
                "units": "Hz",
                "temporal_assumptions": "duration_seconds > 0",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "right knee landmark tracking",
                "confidence_handling": "validated within range [0.2, 8.0] Hz",
                "scientific_reference": "Maglischo (2003)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Unilateral right leg kick rate; does not measure bilateral 6-beat phase coordination."
            },
            {
                "name": "stroke_symmetry",
                "category": "global_kinematics",
                "file": "analysis/strategies/*_biomechanics_calculator.py",
                "function": "_evaluate_symmetry",
                "formula": "Freestyle/Back: 100 - |mean(L_elbow_pull) - mean(R_elbow_pull)|; Breast: Insweep elbow diff; Fly: Wrist Y diff",
                "required_landmarks": [13, 14, 15, 16],
                "coordinate_system": "heuristic percentage [0, 100]",
                "units": "percent",
                "temporal_assumptions": "requires bilateral data during pull/insweep/recovery",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "both arms tracked in matching propulsive phase",
                "confidence_handling": "returns None/unavailable if unilateral data missing",
                "scientific_reference": "Seifert et al. (2005); Psycharakis & Sanders (2008)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Kinematic angular/spatial symmetry index rather than Robinson kinetic symmetry index."
            },
            {
                "name": "average_body_roll",
                "category": "stroke_specific",
                "file": "analysis/strategies/backstroke_biomechanics_calculator.py",
                "function": "calculate_global_metrics",
                "formula": "mean(body_roll across valid frames)",
                "required_landmarks": [11, 12],
                "coordinate_system": "2D normalized image space",
                "units": "degrees",
                "temporal_assumptions": "valid backstroke frames",
                "applicable_strokes": ["Backstroke"],
                "min_evidence_required": "at least 1 valid body roll measurement",
                "confidence_handling": "valid if avg_roll > 0",
                "scientific_reference": "Psycharakis & Sanders (2010); Gonjo et al. (2020)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Planar projection of backstroke shoulder roll."
            },
            {
                "name": "glide_ratio",
                "category": "stroke_specific",
                "file": "analysis/strategies/breaststroke_biomechanics_calculator.py",
                "function": "calculate_global_metrics",
                "formula": "glide_frames / total_frames",
                "required_landmarks": [15, 16, 11, 12],
                "coordinate_system": "temporal ratio [0.0, 1.0]",
                "units": "ratio",
                "temporal_assumptions": "total_frames > 0",
                "applicable_strokes": ["Breaststroke"],
                "min_evidence_required": "breaststroke phase classification",
                "confidence_handling": "status marked available",
                "scientific_reference": "Leblanc et al. (2005); Seifert et al. (2007)",
                "classification": "VALID",
                "audit_notes": "Directly reflects breaststroke streamline efficiency and stroke cadence."
            },
            {
                "name": "max_knee_bend_deg",
                "category": "stroke_specific",
                "file": "analysis/strategies/breaststroke_biomechanics_calculator.py",
                "function": "calculate_global_metrics",
                "formula": "max(180.0 - right_knee_angle)",
                "required_landmarks": [24, 26, 28],
                "coordinate_system": "2D angle",
                "units": "degrees",
                "temporal_assumptions": "knee tracked during kick preparation",
                "applicable_strokes": ["Breaststroke"],
                "min_evidence_required": "valid right knee measurements",
                "confidence_handling": "valid if max_bend > 0",
                "scientific_reference": "Maglischo (2003)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Measures peak whip kick preparation angle relative to anatomical extension."
            },
            {
                "name": "hip_undulation_amplitude",
                "category": "stroke_specific",
                "file": "analysis/strategies/butterfly_biomechanics_calculator.py",
                "function": "calculate_global_metrics",
                "formula": "max(mid_hip_y) - min(mid_hip_y)",
                "required_landmarks": [23, 24],
                "coordinate_system": "normalized vertical displacement",
                "units": "body_length",
                "temporal_assumptions": "len(hip_y_values) > 10",
                "applicable_strokes": ["Butterfly"],
                "min_evidence_required": "at least 10 valid frames with hip landmarks",
                "confidence_handling": "status unavailable if frames <= 10",
                "scientific_reference": "Sanders et al. (1995); Alves et al. (2006)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Measures dolphin kick pelvic displacement; assumes stationary vertical camera framing."
            },
            {
                "name": "avg_wrist_asymmetry",
                "category": "stroke_specific",
                "file": "analysis/strategies/butterfly_biomechanics_calculator.py",
                "function": "calculate_global_metrics",
                "formula": "mean(|L_WRIST.y - R_WRIST.y|)",
                "required_landmarks": [15, 16],
                "coordinate_system": "2D image space normalized",
                "units": "image_space",
                "temporal_assumptions": "simultaneous wrist tracking",
                "applicable_strokes": ["Butterfly"],
                "min_evidence_required": "both wrists visible in valid frames",
                "confidence_handling": "status unavailable if no wrist data",
                "scientific_reference": "UNVERIFIED",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Indicates bilateral hand clearance disparity during butterfly recovery."
            },
            {
                "name": "overall_score",
                "category": "coaching_score",
                "file": "analysis/strategies/*_scoring_engine.py",
                "function": "generate_report",
                "formula": "Freestyle: weighted sum of symmetry (0.20), pull elbow (0.25), recovery shoulder (0.20), kick (0.15), hip (0.20). Back/Breast/Fly: 100 minus specific technique deductions.",
                "required_landmarks": [11, 12, 13, 14, 15, 16, 23, 24, 25, 26],
                "coordinate_system": "composite score [0, 100]",
                "units": "score_points",
                "temporal_assumptions": "requires completed_cycles >= 1",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "at least 1 full stroke cycle and minimum reliability",
                "confidence_handling": "strictly returns None (INSUFFICIENT_EVIDENCE) if 0 cycles detected",
                "scientific_reference": "UNVERIFIED",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Heuristic composite score configured for coaching feedback; zero-fallback prevents fabrication."
            },
            {
                "name": "dropped_elbow_error",
                "category": "movement_error",
                "file": "analysis/strategies/freestyle_scoring_engine.py",
                "function": "generate_report",
                "formula": "pull_elbow_angle not in [90.0, 120.0]",
                "required_landmarks": [11, 12, 13, 14, 15, 16],
                "coordinate_system": "angle degrees",
                "units": "boolean_trigger",
                "temporal_assumptions": "Pull phase",
                "applicable_strokes": ["Freestyle"],
                "min_evidence_required": "Pull phase frames with valid elbow angle",
                "confidence_handling": "Medium severity error",
                "scientific_reference": "Maglischo (2003)",
                "classification": "VALID",
                "audit_notes": "Standard high-elbow catch biomechanical principle."
            },
            {
                "name": "recovery_reach_error",
                "category": "movement_error",
                "file": "analysis/strategies/freestyle_scoring_engine.py",
                "function": "generate_report",
                "formula": "recovery_shoulder_angle not in [140.0, 180.0]",
                "required_landmarks": [11, 12, 13, 14, 23, 24],
                "coordinate_system": "angle degrees",
                "units": "boolean_trigger",
                "temporal_assumptions": "Recovery phase",
                "applicable_strokes": ["Freestyle"],
                "min_evidence_required": "Recovery phase frames with valid shoulder angle",
                "confidence_handling": "Medium severity error",
                "scientific_reference": "Maglischo (2003)",
                "classification": "VALID",
                "audit_notes": "Identifies collapsed recovery or truncated extension."
            },
            {
                "name": "knee_bend_error",
                "category": "movement_error",
                "file": "analysis/strategies/freestyle_scoring_engine.py",
                "function": "generate_report",
                "formula": "kick_knee_angle not in [130.0, 175.0]",
                "required_landmarks": [23, 24, 25, 26, 27, 28],
                "coordinate_system": "angle degrees",
                "units": "boolean_trigger",
                "temporal_assumptions": "timeline frames",
                "applicable_strokes": ["Freestyle"],
                "min_evidence_required": "valid knee angle measurements",
                "confidence_handling": "Medium severity error",
                "scientific_reference": "Maglischo (2003)",
                "classification": "VALID",
                "audit_notes": "Bicycle kicking detection in freestyle flutter kick."
            },
            {
                "name": "asymmetrical_pull_error",
                "category": "movement_error",
                "file": "analysis/strategies/freestyle_scoring_engine.py",
                "function": "generate_report",
                "formula": "stroke_symmetry < 80.0",
                "required_landmarks": [13, 14, 15, 16],
                "coordinate_system": "symmetry percent",
                "units": "boolean_trigger",
                "temporal_assumptions": "bilateral pull phases",
                "applicable_strokes": ["Freestyle"],
                "min_evidence_required": "valid symmetry metric",
                "confidence_handling": "High severity error",
                "scientific_reference": "Seifert et al. (2005)",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Coaching threshold for significant bilateral asymmetry."
            },
            {
                "name": "analysis_reliability_score",
                "category": "reliability_engine",
                "file": "analysis/reliability_engine.py",
                "function": "evaluate",
                "formula": "0.25*FrameCoverage + 0.25*PoseValidity + 0.20*LandmarkVisibility + 0.15*TemporalStability + 0.15*CycleQuality",
                "required_landmarks": [0, 11, 12, 13, 14, 15, 16, 23, 24, 25, 26, 27, 28],
                "coordinate_system": "weighted empirical index [0, 100]",
                "units": "percent",
                "temporal_assumptions": "entire video timeline",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "video metadata and frames list",
                "confidence_handling": "gates report confidence level (High >= 70, Medium >= 40, Low < 40)",
                "scientific_reference": "UNVERIFIED",
                "classification": "VALID",
                "audit_notes": "Transparent, mathematically bounded empirical reliability formulation."
            },
            {
                "name": "frame_coverage_pct",
                "category": "reliability_engine",
                "file": "analysis/reliability_engine.py",
                "function": "_calculate_frame_coverage",
                "formula": "(valid_frames / total_frames) * 100",
                "required_landmarks": [],
                "coordinate_system": "percentage ratio",
                "units": "percent",
                "temporal_assumptions": "total_frames > 0",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "processed frame list",
                "confidence_handling": "component of reliability formula",
                "scientific_reference": "UNVERIFIED",
                "classification": "VALID",
                "audit_notes": "Quantifies completeness of video tracking."
            },
            {
                "name": "pose_validity_pct",
                "category": "reliability_engine",
                "file": "analysis/reliability_engine.py",
                "function": "_calculate_pose_validity",
                "formula": "(valid_frames / total_frames) * 100",
                "required_landmarks": [11, 12, 23, 24],
                "coordinate_system": "percentage ratio",
                "units": "percent",
                "temporal_assumptions": "total_frames > 0",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "landmark confidence threshold >= 0.5",
                "confidence_handling": "component of reliability formula",
                "scientific_reference": "UNVERIFIED",
                "classification": "VALID",
                "audit_notes": "Reflects anatomical validity of detected keypoints."
            },
            {
                "name": "landmark_visibility_pct",
                "category": "reliability_engine",
                "file": "analysis/reliability_engine.py",
                "function": "_calculate_landmark_visibility",
                "formula": "mean(landmark.visibility across all keypoints in valid frames) * 100",
                "required_landmarks": [0, 11, 12, 13, 14, 15, 16, 23, 24, 25, 26, 27, 28],
                "coordinate_system": "mean visibility [0, 100]",
                "units": "percent",
                "temporal_assumptions": "valid frames",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "MediaPipe visibility scores",
                "confidence_handling": "component of reliability formula",
                "scientific_reference": "UNVERIFIED",
                "classification": "VALID",
                "audit_notes": "Direct measure of occlusion and water splash interference."
            },
            {
                "name": "temporal_stability_pct",
                "category": "reliability_engine",
                "file": "analysis/reliability_engine.py",
                "function": "_calculate_temporal_stability",
                "formula": "100 - jitter_penalty(landmark_velocity_variance)",
                "required_landmarks": [11, 12, 15, 16],
                "coordinate_system": "smoothness score [0, 100]",
                "units": "percent",
                "temporal_assumptions": "consecutive frame transitions",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "consecutive valid frames",
                "confidence_handling": "component of reliability formula",
                "scientific_reference": "UNVERIFIED",
                "classification": "NEEDS_VALIDATION",
                "audit_notes": "Empirical heuristic for kinematic trajectory jitter."
            },
            {
                "name": "cycle_quality_pct",
                "category": "reliability_engine",
                "file": "analysis/reliability_engine.py",
                "function": "_calculate_cycle_quality",
                "formula": "min(100.0, (completed_cycles / target_cycles) * 100.0)",
                "required_landmarks": [15, 16],
                "coordinate_system": "scalar score [0, 100]",
                "units": "percent",
                "temporal_assumptions": "completed_cycles",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "detected cycles count",
                "confidence_handling": "penalizes sessions with < 2 cycles",
                "scientific_reference": "UNVERIFIED",
                "classification": "VALID_WITH_LIMITATIONS",
                "audit_notes": "Rewards longer session observation with representative repetitive cycles."
            },
            {
                "name": "measurement_stability_pct",
                "category": "reliability_engine",
                "file": "analysis/reliability_engine.py",
                "function": "evaluate",
                "formula": "coefficient_of_variation_penalty(angles_variance)",
                "required_landmarks": [11, 12, 13, 14, 23, 24, 25, 26],
                "coordinate_system": "stability score [0, 100]",
                "units": "percent",
                "temporal_assumptions": "valid angle timeseries",
                "applicable_strokes": ["Freestyle", "Backstroke", "Breaststroke", "Butterfly"],
                "min_evidence_required": "calculated angles timeseries",
                "confidence_handling": "included in measurement breakdown",
                "scientific_reference": "UNVERIFIED",
                "classification": "NEEDS_VALIDATION",
                "audit_notes": "Heuristic stability indicator based on inter-frame angle variance."
            },
            {
                "name": "butterfly_symmetry_normalization_factor",
                "category": "stroke_specific",
                "file": "analysis/strategies/butterfly_biomechanics_calculator.py",
                "function": "_evaluate_symmetry",
                "formula": "sym_score = max(0.0, 100.0 - (avg_diff / 0.3) * 100.0)",
                "required_landmarks": [15, 16],
                "coordinate_system": "2D normalized image space",
                "units": "percent",
                "temporal_assumptions": "bilateral wrist tracking",
                "applicable_strokes": ["Butterfly"],
                "min_evidence_required": "both wrists tracked",
                "confidence_handling": "returns score [0, 100]",
                "scientific_reference": "UNVERIFIED",
                "classification": "UNVERIFIED",
                "audit_notes": "The 0.3 divisor is an unverified empirical scaling constant representing 30% of normalized image height. While functional as a heuristic coaching penalty, it lacks a formal published biomechanical derivation."
            }
        ]
    }
    
    priority_metric_names = {
        "left_elbow", "right_elbow", "left_knee", "right_knee",
        "left_shoulder", "right_shoulder", "body_roll", "body_roll_3d",
        "stroke_phase", "completed_cycles", "avg_cycle_duration_ms",
        "stroke_rate", "stroke_length"
    }
    for m in baseline["metrics"]:
        m["mathematical_validity"] = "VALID"
        m["implementation_validity"] = "VALID"
        m["empirical_validation_status"] = "NOT_VALIDATED — INSUFFICIENT GROUND TRUTH"
        m["ground_truth_in_repo"] = False
        m["is_priority_metric"] = m["name"] in priority_metric_names

    baseline["empirical_validation_summary"] = {
        "VALIDATED": 0,
        "VALIDATED_WITH_LIMITATIONS": 0,
        "NOT_VALIDATED": 41,
        "FAILED_VALIDATION": 0,
        "reason": "Absence of paired physical Ground Truth datasets (3D optoelectronic mocap / certified manual frame annotations) in repository"
    }
    baseline["scientific_safety_gate"] = {
        "allowed_to_claim_scientifically_validated": False,
        "policy": "No metric may be described as scientifically validated unless paired physical ground truth exists"
    }

    out_path = Path("data/reference/biomechanics_metric_baseline.json")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(baseline, f, indent=2)
    print(f"Successfully created {out_path} with {len(baseline['metrics'])} audited metrics.")

if __name__ == "__main__":
    create_baseline()
